In [ ]:
#Numpy Array Basics
# importing numpy #pip install numpy # conda install numpy
import numpy as np 
#import array  #alias  #include<stdio.h> include <math.h>     [7,8.5,'sasi']  list , array , series ,dataframe

# Defining 1D array  # scalar
my1DArray = np.array() # row , list  #1*4 series 
print(my1DArray)

# Defining and printing 2D array #vector
my2DArray = np.array([[1, 2, 3, 4], [2, 4, 9, 16], [4, 8, 18, 32]]) # 3* 4 = 1 matrix 300 *400 = one matrix
print(my2DArray)

#Defining and printing 3D array # matrix
my3Darray = np.array([[[ 1, 2 , 3 , 4],[ 5 , 6 , 7  ,8]], [[ 1,  2,  3,  4],[ 9, 10, 11, 12]]]) #2*4,2 = 2 matrix
print(my3Darray.ndim)



[ 1  8 27 64]
[[ 1  2  3  4]
 [ 2  4  9 16]
 [ 4  8 18 32]]
3


[7,8.0,9.7]  array ;  series ; 1 row;  record

In [ ]:
my2DArray.ndim

2

In [ ]:
my2DArray.shape

(3, 4)

In [ ]:
my1DArray.shape #(4,)

(4,)

In [ ]:
a = [1,6,7.6,"sdas","jhgjg"]

In [ ]:
a

[1, 6, 7.6, 'sdas', 'jhgjg']

In [ ]:
a.ndim

AttributeError: ignored

In [ ]:
b = np.array(a)

In [ ]:
b.ndim    # []

1

In [ ]:
b.dtype

dtype('<U32')

In [ ]:
s = [4,5,'sa'] #series , list , array

In [ ]:
type(s)

list

In [ ]:
 v = np.array(s)

In [ ]:
type(v)

numpy.ndarray

In [ ]:
# Print out memory address
print(my2DArray.data)
print(my2DArray)

# Print the shape of array
print(my2DArray.shape)

# Print out the data type of the array
print(my2DArray.dtype)


[[ 1  2  3  4]
 [ 2  4  9 16]
 [ 4  8 18 32]]
(3, 4)
int64


In [ ]:
my2DArray.shape

(3, 4)

In [ ]:
print(my2DArray.strides)

(32, 8)


what is stride of array?  It is the number of locations in memory between 
beginnings of successive array elements, measured in bytes or in units of the
size of the array's elements
"""


In [ ]:
#Array using numpy built-in functions
# Array of ones
ones = np.ones((4,3,4)) # row , colum, no of matrix
print(ones)

# Array of zeros
zeros = np.zeros((5,3,4),dtype=np.int16) # 2, 50,500,578687669696
print(zeros)

# Array with random values
s =np.random.random((2,2))
            
# Empty array
emptyArray = np.empty((3,2))
print(emptyArray)

# Full array
fullArray = np.full((2,2),7)
print(fullArray)

# Array of evenly-spaced values
evenSpacedArray = np.arange(10,25,5)
print(evenSpacedArray)

# Array of evenly-spaced values
evenSpacedArray2 = np.linspace(0,2,9)
print(evenSpacedArray2)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
[[7.74860419e-304 7.74860419e-304]
 [7.74860419e-304 7.74860419e-304]
 [7.74860419e-304 7.74860419e-304]]
[[7 7]
 [7 7]]
[10 15 20]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [ ]:
zeros

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int16)

In [ ]:
s

array([[0.3510922 , 0.57800863],
       [0.10633287, 0.5591529 ]])

In [ ]:
emptyArray

array([[4.67020372e-310, 4.94065646e-324],
       [4.94065646e-324, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

In [ ]:
s

array([[0.19097417, 0.34202638],
       [0.58400162, 0.64276739]])

In [ ]:
r = np.array([[[5,3,9,10],[6,7,8,3],[7,5,7,9]],[[7,6,5,9],[6,7,8,6],[4,7,8,9]]],dtype = complex) #3 *4 , 1*4



r.ndim # 3
r.shape  #67+-9kly
r



array([[[ 5.+0.j,  3.+0.j,  9.+0.j, 10.+0.j],
        [ 6.+0.j,  7.+0.j,  8.+0.j,  3.+0.j],
        [ 7.+0.j,  5.+0.j,  7.+0.j,  9.+0.j]],

       [[ 7.+0.j,  6.+0.j,  5.+0.j,  9.+0.j],
        [ 6.+0.j,  7.+0.j,  8.+0.j,  6.+0.j],
        [ 4.+0.j,  7.+0.j,  8.+0.j,  9.+0.j]]])

In [ ]:

i = 0
j = 1
k = 1
r[i,j,k]

(7+0j)

In [ ]:
t = np.array([[5,3,9,10],[6,7,8,3],[7,5,7,9]]) # matrix
t

array([[ 5,  3,  9, 10],
       [ 6,  7,  8,  3],
       [ 7,  5,  7,  9]])

In [ ]:
t[1:2] # end-1

array([[6, 7, 8, 3]])

In [ ]:
y = np.array([5,3,9,10]) #series
y

array([ 5,  3,  9, 10])

In [ ]:
r.ndim

3

In [ ]:
r.shape

(3, 4)

In [ ]:
r[0,:,:]

array([[ 5.+0.j,  3.+0.j,  9.+0.j, 10.+0.j],
       [ 6.+0.j,  7.+0.j,  8.+0.j,  3.+0.j],
       [ 7.+0.j,  5.+0.j,  7.+0.j,  9.+0.j]])

In [ ]:
t % 2 == 0

array([[False, False, False,  True],
       [ True, False,  True, False],
       [False, False, False, False]])

In [ ]:
t[t %2 == 0] #show s the value whever the condition is true 

array([10,  6,  8])

In [ ]:
t

array([[ 5,  3,  9, 10],
       [ 6,  7,  8,  3],
       [ 7,  5,  7,  9]])

In [ ]:
my_indeces = [2,1]

In [ ]:
t[my_indeces]

array([[7, 5, 7, 9],
       [6, 7, 8, 3]])

In [ ]:
# Broadcasting in NumPy
#Scalar and One-Dimensional Array
import array

In [ ]:
a = np.array([1, 2, 3])

In [ ]:
b = np.array([8,7,9])

In [ ]:
c = a + b

In [ ]:
c

array([ 9,  9, 12])

In [ ]:
#Scalar and Two-Dimensional Array

In [ ]:
k = np.array([5,3,6,7,9])
j=np.array([4,2,6,9,8])

In [ ]:
g = k+j

In [ ]:
g

array([ 9,  5, 12, 16, 17])

array([[ 63, 320,  83],
       [ 77, 484, 102],
       [ 84, 248, 117]])